#!/usr/bin/env bash

for P in `ls | grep cu$`
do
	FILE_NAME="$P.res"
	rm $FILE_NAME
	touch $FILE_NAME

	echo "$P"
	echo ""
	nvcc  $P  -O3 --compiler-options "-std=c++98" -I./ > /dev/null 2>&1
	echo "N,time"
	for N in 16 32 64 #128 256 512 1024 2048
	do

		printf "%d,%s" "$N "./a.out $N | tee -a $FILE_NAME
	done
	rm ./a.out
	echo ""
done
